version: '3'

services:
  haraka-mail:
    image: instrumentisto/haraka:3.0.2
    restart: always
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./data/plugins:/etc/haraka/plugins:rw
      - ./data/config:/etc/haraka/config:rw
      - ./index.js:/etc/haraka/plugins/resque.js:ro
    command:
      [
        "bash /etc/haraka/config/mystart.sh"
      ]

# this is a trick to initialize our data with data from haraka image
  haraka-init:
    restart: 'no'
    image: instrumentisto/haraka:3.0.2
    volumes:
      - ./data:/data:rw
      - ./defaults:/1defaults:ro
    command:
      [
        "bash /data/myinit.sh"
      ]
