version: '3'

services:
  bouncer:
    image: instrumentisto/haraka:3.0.2
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost/?purge=true | grep -q OK"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./index.js:/etc/haraka/plugins/resque.js
    command:
      [
        "bash",
        "-c",
        "cd /etc/haraka && npm install axios",
      ]

